name: bootcamp 26 CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: docker login to github container registry
        uses: docker/login-action/@v2
        with:
         registry: ${{ secrets.REGISTRY }}
         username: ${{ secrets.REGISTRY_USERNAME }}
         password: ${{ secrets.REGISTRY_TOKEN }}

      - name: maven install
        working-directory: ./backend
        run: mvn clean install -DskipTests
      
      - name: build mysql
        working-directory: ./database
        run: docker build . -t ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/bootcamp-26-db:latest
      
      - name: build backend
        working-directory: ./backend
        run: docker build . -t ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/bootcamp-26-backend:latest
      
      - name: build frontend
        working-directory: ./frontend
        run: docker build . -t ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/bootcamp-26-frontend:latest

      - name: docker push mysql
        run: docker push ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/bootcamp-26-db:latest
      - name: docker push backend
        run: docker push ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/bootcamp-26-backend:latest
      - name: docker push frontend
        run: docker push ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/bootcamp-26-frontend:latest
      
      - name: frontend
        run: ssh -i "${{ secrets.EC2_SSH_KEY }}" ${{ secrets.EC2_USERNAME }}@${{ secrets.HOST_DNS }}

      - name: pull frontend image
        run: docker pull ghcr.io/divya-gariga/bootcamp-26-frontend:latest

      - name: run frontend container
        run: docker run ghcr.io/divya-gariga/bootcamp-26-frontend:latest
      
     